[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'ErichDonGubler/vim-sublime-monokai'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'scrooloose/nerdtree'
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neocomplete'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

# ctags
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

# 構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'

# markdownプレビュー
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

# python構文・コーディング規約チェック
[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# indent可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# HTML/CSS
[[plugins]]
repo = 'vim-scripts/HTML-AutoCloseTag'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'ruanyl/vim-fixmyjs'

# JSON syntax
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

# mustache / handlebars
[[plugins]]
repo = 'mustache/vim-mustache-handlebars'

# nodejs補完
[[plugins]]
repo = 'myhere/vim-nodejs-complete'

# VCL
[[plugins]]
repo = 'smerrill/vcl-vim-plugin'

#submode
[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
call submode#map('bufmove', 'n', '', '>', '<C-w>>')
call submode#map('bufmove', 'n', '', '<', '<C-w><')
'''

#editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

#comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

#visualize move
[[plugins]]
repo = 't9md/vim-textmanip'

